plugins/kubevpn.yaml

Update report
- Updated with *today's* date

feat: update krew index version

---

plugins/kubevpn.yaml

update report
- update krew index version to refs/tags/v1.1.29

feat: update krew index version to refs/tags/v1.1.29

---

plugins/kubevpn.yaml

update report
- update krew index version to refs/tags/v1.1.30

feat: update krew index version to refs/tags/v1.1.30

---

plugins/kubevpn.yaml

update report
- update krew index version to refs/tags/v1.1.34

feat: update krew index version to refs/tags/v1.1.34

---

plugins/kubevpn.yaml

update report
- update krew index version to refs/tags/v1.1.35

feat: update krew index version to refs/tags/v1.1.35

---

plugins/kubevpn.yaml

update report
- update krew index version to refs/tags/v1.1.36

feat: update krew index version to refs/tags/v1.1.36

---

pkg/handler/connect.go

add server url with dns name and port case. 
fix #79 issue.

fix parseAddrPort error

---

pkg/handler/connect.go

preserver original server name to TLSServerName. 
fix #82

add TLSServerName

---

README.md

update how to test proxy and dev mode.

add some proxy test comments

---

cmd/kubevpn/cmds/quit.go
cmd/kubevpn/cmds/ssh.go
pkg/daemon/handler/ssh.go
pkg/handler/cleaner.go
pkg/upgrade/upgrade.go
pkg/util/image.go
pkg/util/scp.go
pkg/util/upgarde.go

hotfix: fix ssh failed issue

---

plugins/kubevpn.yaml

update report
- update krew index version to refs/tags/v2.1.1

feat: update krew index version to refs/tags/v2.1.1

---

pkg/handler/remote.go

Moved pods watching to after traffic manager pod is created

---

pkg/dns/dns_linux.go

fix: fix linux /etc/resolv.conf not restore bug

---

plugins/kubevpn.yaml

update report
- update krew index version to refs/tags/v2.2.1

feat: update krew index version to refs/tags/v2.2.1

---

pkg/daemon/action/clone.go
pkg/daemon/action/connect-fork.go
pkg/daemon/action/connect.go
pkg/daemon/action/proxy.go
pkg/mesh/controller.go

feat: set envoy log level dynamic

---

pkg/webhook/dhcp.go

fix: add lock in case of rent same ip

---

cmd/kubevpn/cmds/controlplane.go
cmd/kubevpn/cmds/serve.go
cmd/kubevpn/cmds/webhook.go
pkg/handler/dhcp.go
pkg/handler/remote.go
pkg/util/log.go
pkg/util/pod.go
pkg/webhook/convert.go
pkg/webhook/dhcp.go
pkg/webhook/mutateadmissionwebhook.go
pkg/webhook/pods.go

fix: fix rent same ip

---

README.md

Add missing commas, correction of spelling errors

Add missing commas, correction of spelling errors

---

plugins/kubevpn.yaml

update report
- update krew index version to refs/tags/v2.2.3

feat: update krew index version to refs/tags/v2.2.3

---

pkg/core/gvisortcphandler.go
pkg/core/gvisorudpforwarder.go
pkg/core/gvisorudphandler.go
pkg/util/timeout.go

* feat: transfer gvisor udp packet without header
---------

feat: transfer gvisor udp packet without customized header (#195)

---

pkg/handler/connect.go
pkg/handler/remote.go

fix: fix proxy mode bug

---

plugins/kubevpn.yaml

update report
- update krew index version to refs/tags/v2.2.8

feat: update krew index version to refs/tags/v2.2.8

---

pkg/handler/connect.go
pkg/tun/tun_linux.go
pkg/tun/tun_windows.go
pkg/util/net_others.go
pkg/util/net_windows.go

feat: not set ipv6 if ipv6 is not enable on linux

---

plugins/kubevpn.yaml

update report
- update krew index version to refs/tags/v2.2.9

feat: update krew index version to refs/tags/v2.2.9

---

plugins/kubevpn.yaml

update report
- update krew index version to refs/tags/v2.2.11

feat: update krew index version to refs/tags/v2.2.11

---

pkg/upgrade/upgrade.go
pkg/util/util.go

hotfix: fix upgrade use rename but cross device

---

cmd/kubevpn/cmds/upgrade.go
pkg/upgrade/upgrade.go
pkg/util/util.go

hotfix: fix upgrade

---

pkg/handler/connect.go

hotfix: use pod ip as dns server if service ip is unreachable

---

plugins/kubevpn.yaml

update report
- update krew index version to refs/tags/v2.2.19

feat: update krew index version to refs/tags/v2.2.19

---

cmd/kubevpn/cmds/clone.go
cmd/kubevpn/cmds/connect.go
cmd/kubevpn/cmds/proxy.go
pkg/dev/options.go
pkg/ssh/ssh.go
pkg/util/ns.go

feat: add apiserver ip to route table if ssh info is not empty

---

cmd/kubevpn/cmds/clone.go
cmd/kubevpn/cmds/connect.go
cmd/kubevpn/cmds/controlplane.go
cmd/kubevpn/cmds/dev.go
cmd/kubevpn/cmds/proxy.go
cmd/kubevpn/cmds/serve.go
cmd/kubevpn/cmds/syncthing.go
cmd/kubevpn/cmds/webhook.go
pkg/config/config.go
pkg/core/gvisoricmpforwarder.go
pkg/core/gvisorstack.go
pkg/core/gvisortcpforwarder.go
pkg/core/gvisortcphandler.go
pkg/core/gvisortunendpoint.go
pkg/core/gvisorudpforwarder.go
pkg/core/gvisorudphandler.go
pkg/core/tcphandler.go
pkg/core/tunhandler.go
pkg/core/tunhandlerclient.go
pkg/dev/options.go
pkg/handler/clone.go
pkg/handler/connect.go
pkg/util/net.go
pkg/util/util.go

feat: use gvisor parse network packet in pod

---

cmd/kubevpn/cmds/daemon.go
pkg/daemon/action/quit.go
pkg/dns/dns.go
pkg/dns/dns_unix.go
pkg/handler/connect.go
pkg/util/dns.go
pkg/util/file.go

hotfix: add more resolver on macOS

---

pkg/inject/controller.go
pkg/inject/envoy_ipv4.yaml
pkg/inject/mesh.go
pkg/util/pod.go

hotfix: detect enable ipv6 for envoy

---

pkg/handler/connect.go
pkg/util/net.go
pkg/util/route.go

hotfix: return error if dig extra-domain ip is empty

---

pkg/daemon/daemon.go
pkg/dhcp/dhcp.go

hotfix: disable net.DefaultResolver.PreferGo

---

pkg/inject/fargate.go
pkg/inject/label_test.go

use match not equal to find svc by pod label in fargate mode

---

pkg/daemon/elevate/elevate_others.go

fix: fix daemon process unexpected exit on linux

---

pkg/util/pod.go

try to solve issue portforward bug. 
https://www.reddit.com/r/kubernetes/comments/1isxgo2/comment/mdzd83s/?context=3

hotfix: default use spdy not websocket to portforward

---

pkg/handler/connect.go

Unable to modify deployment due to error: map: map[] does not contain declared merge key: name
issue: https://github.com/kubernetes/kubernetes/issues/98963

hotfix: fix auto upgrade deploy image

---

.github/workflows/coverage.yml
.github/workflows/test.yml
Makefile
README.md
README_ZH.md
build/test.Dockerfile
charts/kubevpn/values.yaml
pkg/config/config.go
pkg/daemon/handler/ssh_test.go
pkg/test/pod.yaml
samples/bookinfo.yaml

feat: change default container image

---

pkg/handler/connect.go

If can not dig extra-domain, try to find dns entry in ingress record

feat: options extra-domain support ingress record

---

pkg/dns/dns.go
pkg/handler/connect.go

feat: support service type externalName

---

pkg/dns/forwardserver.go

hotfix: fix dns slow

---

build/Dockerfile
build/test.Dockerfile

hotfix: install missing command dig

---

pkg/handler/connect.go

https://github.com/kubenetworks/kubevpn/issues/132#issuecomment-2795970630

hotfix: fix parse dig command output

---

plugins/kubevpn.yaml

update report
- update krew index version to refs/tags/v2.7.5

feat: update krew index version to refs/tags/v2.7.5

---

pkg/util/ns.go

hotfix: fix create temp kubeconfig

---

pkg/core/gvisortunendpoint.go

hotfix: handle not found route packet with gVisor instead of drop it

---

cmd/kubevpn/cmds/webhook.go
pkg/controlplane/processor.go
pkg/controlplane/server.go
pkg/daemon/action/clone.go
pkg/daemon/action/connect-fork.go
pkg/daemon/action/connect.go
pkg/daemon/action/proxy.go
pkg/handler/clone.go
pkg/handler/connect.go
pkg/handler/function_test.go
pkg/handler/remote.go
pkg/inject/controller.go
pkg/inject/exchange.go
pkg/inject/fargate.go
pkg/inject/mesh.go
pkg/inject/proxy.go
pkg/util/cidr.go
pkg/util/cidr_test.go
pkg/webhook/main.go
pkg/webhook/mutateadmissionwebhook.go
pkg/webhook/pods.go

feat: proxy mode use traffic-manager pod image

---

cmd/kubevpn/cmds/status.go
pkg/daemon/action/connect.go
pkg/daemon/action/disconnect.go
pkg/daemon/action/proxy.go
pkg/daemon/action/reset.go
pkg/daemon/action/sync.go
pkg/daemon/action/uninstall.go
pkg/ssh/ssh.go

hotfix: fix --remote-kubeconfig override temp kubeconfig
